version: '3'

services:
  db:
    image: postgres:11
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=checkerdb
      - POSTGRES_USER=checkeruser
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data/
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  data:
